containernet:
  default:
    image: containernet:latest
    privileged: true
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
  customized_example: # An example of a customized Containernet image configuration.
    image: your_example.com/your_example:latest
    privileged: true
    containernet_repo_from_user: true # If true, will mount `containernet_repo_path`.
    containernet_repo_path: "/home/{user_name}/workspace/containernet"
    network_mode: "host"
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"
