name: Oasis CI
on:
  pull_request:
    branches: ["main", "dev"]
    types:
      - opened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**.md"
      - "**.json"
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**.md"
      - "**.json"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  oasis-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: sync git-lfs
        run: git lfs install && git lfs pull
      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10.14"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r ${{github.workspace}}/src/containernet/requirements.txt
      - name: Restore Docker Images
        id: cached-docker-images
        uses: actions/cache@v4
        with:
          path: ${{github.workspace}}/images/
          key: docker_cache-${{ hashFiles('**/Dockerfile.**') }}
      - name: Build Docker Images
        if: steps.cached-docker-images.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/
        run: |
          mkdir -p ${{github.workspace}}/images/
          docker build -t containernet:latest -f Dockerfile.containernet .
          docker build -t ubuntu-generic:latest -f Dockerfile.ubuntu-generic .
          docker image save containernet:latest --output ${{github.workspace}}/images/containernet.tar
          docker image save ubuntu-generic:latest --output ${{github.workspace}}/images/ubuntu-generic.tar
          docker images
      - name: Load Docker Images
        working-directory: ${{github.workspace}}/
        if: steps.cached-docker-images.outputs.cache-hit == 'true'
        run: |
          docker image load --input ./images/containernet.tar
          docker image load --input ./images/ubuntu-generic.tar
      - name: Loading secrets
        run: |
          echo "Hardware_info=${{secrets.BATS_HARDWARE_INFO}}" >> ${{github.workspace}}/test/rootfs/etc/cfg/licence
          echo "Licence_id=${{secrets.BATS_LICENCE_ID}}" >> ${{github.workspace}}/test/rootfs/etc/cfg/licence
      - name: SSHPing tests
        working-directory: ${{github.workspace}}/
        run: |
          ./src/tools/run_test.sh protocol-sshping-test.yaml --cleanup --no-privilege
      - name: SCP test
        working-directory: ${{github.workspace}}/
        run: |
          ./src/tools/run_test.sh protocol-scp-test.yaml --cleanup --no-privilege
      - name: Throughput tests
        working-directory: ${{github.workspace}}/
        run: |
          ./src/tools/run_test.sh protocol-ci-test.yaml --cleanup --no-privilege
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ci-test-logs
          path: |
            ${{github.workspace}}/test_results/**
          retention-days: 1
